// Capability catalog (SPEC.md §4.5 / auth task). Roles map to default sets; per-user
// overrides (grant/revoke) refine them. See role-capabilities.ts.
export enum Capability {
  // Inventory
  INVENTORY_CREATE = 'INVENTORY_CREATE',
  INVENTORY_EDIT = 'INVENTORY_EDIT',
  INVENTORY_DELETE = 'INVENTORY_DELETE',
  INVENTORY_VIEW = 'INVENTORY_VIEW',
  INVENTORY_BULK_IMPORT = 'INVENTORY_BULK_IMPORT',
  // Planning
  CAMPAIGN_CREATE = 'CAMPAIGN_CREATE',
  CAMPAIGN_EDIT = 'CAMPAIGN_EDIT',
  CAMPAIGN_VIEW = 'CAMPAIGN_VIEW',
  CAMPAIGN_EXPORT = 'CAMPAIGN_EXPORT',
  KPI_ESTIMATE = 'KPI_ESTIMATE',
  // Booking
  BOOKING_REQUEST = 'BOOKING_REQUEST',
  BOOKING_APPROVE = 'BOOKING_APPROVE',
  BOOKING_CANCEL = 'BOOKING_CANCEL',
  BOOKING_VIEW = 'BOOKING_VIEW',
  // POP
  POP_CAPTURE = 'POP_CAPTURE',
  POP_VIEW = 'POP_VIEW',
  POP_MANAGE = 'POP_MANAGE',
  // Monitoring
  MONITORING_VIEW = 'MONITORING_VIEW',
  ISSUE_CREATE = 'ISSUE_CREATE',
  ISSUE_RESOLVE = 'ISSUE_RESOLVE',
  ISSUE_VIEW = 'ISSUE_VIEW',
  // Marketplace
  MARKETPLACE_VIEW = 'MARKETPLACE_VIEW',
  MARKETPLACE_MANAGE = 'MARKETPLACE_MANAGE',
  // Reporting
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_EXPORT = 'REPORT_EXPORT',
  REPORT_MANAGE = 'REPORT_MANAGE',
  // Admin
  ORG_MANAGE = 'ORG_MANAGE',
  USER_MANAGE = 'USER_MANAGE',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  AUDIT_VIEW = 'AUDIT_VIEW',
  REFERENCE_DATA_MANAGE = 'REFERENCE_DATA_MANAGE',
  // Org
  ORG_SETTINGS_EDIT = 'ORG_SETTINGS_EDIT',
  MEMBERSHIP_MANAGE = 'MEMBERSHIP_MANAGE',
  BILLING_MANAGE = 'BILLING_MANAGE',
  // Org self-service (global — granted to any authenticated user, no org context needed)
  ORG_CREATE = 'ORG_CREATE',
  ORG_VIEW = 'ORG_VIEW',
}

export const ALL_CAPABILITIES: Capability[] = Object.values(Capability) as Capability[];
