import * as Joi from 'joi';

export default Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  API_PORT: Joi.number().default(3000),
  API_BASE_URL: Joi.string().default('http://localhost:3000'),
  WEB_BASE_URL: Joi.string().default('http://localhost:3001'),
  JWT_SECRET: Joi.string().min(8).default('change-me-in-dev'),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),
  SESSION_SECRET: Joi.string().min(8).default('change-me-session-dev'),
  AZURE_AD_TENANT_ID: Joi.string().allow('').default(''),
  AZURE_AD_CLIENT_ID: Joi.string().allow('').default(''),
  AZURE_AD_CLIENT_SECRET: Joi.string().allow('').default(''),
  AZURE_AD_REDIRECT_URL: Joi.string().default('http://localhost:3000/api/auth/microsoft/callback'),
  SMTP_HOST: Joi.string().default('localhost'),
  SMTP_PORT: Joi.number().default(1025),
  SMTP_USER: Joi.string().allow('').default(''),
  SMTP_PASS: Joi.string().allow('').default(''),
  MAIL_FROM: Joi.string().default('no-reply@abonten.local'),
  DATABASE_URL: Joi.string().default('postgresql://abonten:abonten@localhost:5432/abonten'),
  REDIS_URL: Joi.string().default('redis://localhost:6379'),
  S3_ENDPOINT: Joi.string().default('http://localhost:9000'),
  S3_BUCKET: Joi.string().default('abonten'),
  S3_REGION: Joi.string().default('us-east-1'),
});
