export const authCopy = {
  en: {
    access: 'Account access',
    hero: 'Your outdoor work, kept in context.',
    intro: 'Sign in with a short code. Your organization and account settings stay with you.',
    expiry: 'A code expires after ten minutes. We never ask you to create or remember a password.',
    about: 'About',
    heading: 'Sign in or create an account',
    codeIntro: 'We’ll send a six-digit code to your work email.',
    email: 'Email address',
    placeholder: 'you@company.com',
    sending: 'Sending code…',
    send: 'Email me a code',
    microsoft: 'Continue with Microsoft',
    unavailable: 'Microsoft sign-in isn’t available. Use an email code instead.',
    different: 'Use a different email',
    inbox: 'Check your inbox',
    sent: 'We sent a code to',
    code: 'Six-digit code',
    checking: 'Checking code…',
    continue: 'Continue',
    resend: 'Send another code',
    context:
      'Your organization context stays with your account. You can switch later if you belong to more than one.',
    generic: 'Something went wrong. Please try again.',
    invalid: 'Invalid or expired sign-in code',
    requestLimit: 'Too many sign-in code requests. Please try again later.',
    verifyLimit: 'Too many verification attempts. Please try again later.',
    authUnavailable: 'Sign-in is temporarily unavailable. Please try again.',
    callbackHeading: 'Finishing sign-in',
    callbackLoading: 'Checking your Microsoft account…',
    callbackMissing:
      'Microsoft sign-in did not return a usable session. Try an email code instead.',
    callbackFailed: 'We could not finish Microsoft sign-in. Try an email code instead.',
    back: 'Return to sign in',
  },
  fr: {
    access: 'Accès au compte',
    hero: 'Votre travail en extérieur, avec son contexte.',
    intro: 'Connectez-vous avec un code court. Votre organisation et vos paramètres vous suivent.',
    expiry: 'Un code expire après dix minutes. Aucun mot de passe à créer ou à retenir.',
    about: 'À propos',
    heading: 'Connectez-vous ou créez un compte',
    codeIntro: 'Nous enverrons un code à six chiffres à votre adresse professionnelle.',
    email: 'Adresse email',
    placeholder: 'vous@entreprise.com',
    sending: 'Envoi du code…',
    send: 'Recevoir un code par email',
    microsoft: 'Continuer avec Microsoft',
    unavailable: 'La connexion Microsoft est indisponible. Utilisez un code envoyé par email.',
    different: 'Utiliser une autre adresse email',
    inbox: 'Consultez votre boîte de réception',
    sent: 'Nous avons envoyé un code à',
    code: 'Code à six chiffres',
    checking: 'Vérification du code…',
    continue: 'Continuer',
    resend: 'Envoyer un nouveau code',
    context:
      'Le contexte de votre organisation reste lié à votre compte. Vous pourrez changer d’organisation si vous en avez plusieurs.',
    generic: 'Un problème est survenu. Réessayez.',
    invalid: 'Code de connexion incorrect ou expiré',
    requestLimit: 'Trop de demandes de code de connexion. Réessayez plus tard.',
    verifyLimit: 'Trop de tentatives de vérification. Réessayez plus tard.',
    authUnavailable: 'La connexion est temporairement indisponible. Réessayez.',
    callbackHeading: 'Finalisation de la connexion',
    callbackLoading: 'Vérification de votre compte Microsoft…',
    callbackMissing: 'Microsoft n’a pas fourni de session utilisable. Essayez un code par email.',
    callbackFailed: 'Impossible de terminer la connexion Microsoft. Essayez un code par email.',
    back: 'Revenir à la connexion',
  },
} as const;
